"""fix:removed self_appraisal text from appraisal table

Revision ID: 470a7e7e937a
Revises: 7cbd5c11e97e
Create Date: 2026-06-29 14:38:11.952013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470a7e7e937a'
down_revision: Union[str, Sequence[str], None] = '7cbd5c11e97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appraisals', 'self_appraisal_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appraisals', sa.Column('self_appraisal_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
