"""fix:moved idp_text from lead_feedback to appraisal

Revision ID: 73b987a29b0f
Revises: 470a7e7e937a
Create Date: 2026-06-29 14:45:02.359194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73b987a29b0f"
down_revision: Union[str, Sequence[str], None] = "470a7e7e937a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appraisals", sa.Column("idp_text", sa.Text(), nullable=True))
    op.drop_column("lead_feedbacks", "idp_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lead_feedbacks", sa.Column("idp_text", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("appraisals", "idp_text")
    # ### end Alembic commands ###
